# Generated by Django 3.2.9 on 2021-11-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20211112_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resposta",
            name="enquete_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas",
                to="app.enquete",
            ),
        ),
    ]
